### ISSUE TITLE
spec.containers[x].execs contains the same entry multiple times

### ISSUE THREAD

**Issue by slashben** [kubescape/kapprofiler#29]
In version v0.0.25 the application profile looks like this:

```
spec:                                                                                                                              
  containers:                                                                                                                      
  - execs:                                                                                                                         
    - args:                                                                                                                        
      - -liveness                                                                                                                  
      envs: []                                                                                                                     
      path: /bin/gadgettracermanager                                                                                               
    - args:                                                                                                                        
      - -liveness                                                                                                                  
      envs: []                                                                                                                     
      path: /bin/gadgettracermanager                                                                                               
    - args:                                                                                                                        
      - -liveness                                                                                                                  
      envs: []                                                                                                                     
      path: /bin/gadgettracermanager      
```

It looks like the same entry is added over and over again.

@Bezbran @amitschendel , this can be either due to PR #24 or #22
